#!/bin/sh

Colour00="#1c1c1c" #Black 
Colour01="#a54242" #Red
Colour02="#8C9440" #Green
Colour03="#de935f" #Orange
Colour04="#5f819d" #Blue
Colour05="#b294bb" #Purple
Colour06="#8abeb7" #Aqua
Colour07="#969896" #LightGrey 
Colour08="#ffaf00" #DarkGrey
Colour09="#cc6666" #LightRed
Colour10="#b5bd68" #LightGreen
Colour11="#f0c674" #Yellow
Colour12="#81a2be" #LightBlue
Colour13="#b294bb" #LightPurple
Colour14="#8abeb7" #LightAqua
Colour15="#c5c8c6" #White

ColourPalette="${Colour00}:${Colour01}:${Colour02}:${Colour03}:${Colour04}:${Colour05}:${Colour06}:${Colour07}:${Colour08}:${Colour09}:${Colour10}:${Colour11}:${Colour12}:${Colour13}:${Colour14}:${Colour15}"

FG_Colour=$Colour15
BG_Colour=$Colour00

gconftool --set /apps/gnome-terminal/profiles/Default/use_system_font --type bool false
#gconftool --set /apps/gnome-terminal/profiles/Default/bold_color_same_as_fg --type bool true
gconftool --set /apps/gnome-terminal/profiles/Default/font --type string "Monospace 11"
gconftool --set /apps/gnome-terminal/profiles/Default/use_theme_colors --type bool false
gconftool --set /apps/gnome-terminal/profiles/Default/foreground_color --type string $FG_Colour
gconftool --set /apps/gnome-terminal/profiles/Default/background_color --type string $BG_Colour 
#gconftool --set /apps/gnome-terminal/profiles/Default/allow_bold --type bool false
gconftool --set /apps/gnome-terminal/profiles/Default/silent_bell --type bool true
#gconftool --set /apps/gnome-terminal/profiles/Default/bold_color_same_as_fg --type bool true
gconftool --type string --set /apps/gnome-terminal/profiles/Default/palette $ColourPalette 
